version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    restart: always

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ebill_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass

    ports:
      - "3306:3306"

    restart: always
